name: Dev Builds

on:
  push:
    paths:
      - "jals.toml"
      - "build.rhai"
      - "mod.properties"
      - "scripts/**"
      - "src/**"
      - "versions/**"
      - ".github/**"
  pull_request:


jobs:
  build:
    uses: ./.github/workflows/build.yml
